name: halfways
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+4

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http: any
  uuid: ^3.0.6
  intl: ^0.17.0
  geolocator: ^9.0.2
  share_plus: ^6.3.4
  path_provider: ^2.0.14
  cupertino_icons: ^1.0.2
  package_info_plus: ^3.1.2
  shared_preferences: ^2.1.0
  google_maps_flutter: ^2.2.5
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.12.0
  flutter_polyline_points: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#00B1AC"
  image: assets/logos/logo.png

  android_12:
    color: "#00B1AC"
    image: assets/logos/logo.png

flutter_icons:
  image_path: assets/logos/icon.png
  adaptive_icon_background: "#00B1AC"
  adaptive_icon_foreground: assets/logos/icon.png
  android: true
  ios: true

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logos/logo.png
    - assets/logos/icon.png
    - assets/logos/icon_trimmed.png

    - assets/icons/driving.png
    - assets/icons/driving_filled.png
    - assets/icons/transit.png
    - assets/icons/transit_filled.png
    - assets/icons/bicycling.png
    - assets/icons/bicycling_filled.png
    - assets/icons/walking.png
    - assets/icons/walking_filled.png

    - assets/markers/MarkerBasic.png
    - assets/markers/MarkerMidpoint.png
    - assets/markers/MarkerRestaurant.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand.ttf

